name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install

    - name: Lint with flake8
      if: always()
      run: |
        poetry run flake8 .

    - name: Test mypy
      if: always()
      run:  poetry run mypy .

    - name: Test with black
      if: always()
      run: poetry run black --check .

    - name: Test with pytest
      if: always()
      run: poetry run pytest --cov

    - name: Produce coverage XML
      run: poetry run coverage xml
